LibraryProject.MvcWebUI/Controllers/BookController.cs
using LibraryProject.MvcWebUI.Models.Entity;
using LibraryProject.MvcWebUI.Models.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LibraryProject.MvcWebUI.Controllers
{
    public class BookController : Controller
    {
        BaseRepository<Book> bookRepository = new BaseRepository<Book>();
        BaseRepository<Category> categoryRepository = new BaseRepository<Category>();
        public ActionResult Index()
        {
            ViewBag.Categories = categoryRepository.GetList();
            var books = bookRepository.GetList();
            return View(books);
        }

        public ActionResult AddBook()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddBook(Book book)
        {
            bookRepository.Add(book);

            return RedirectToAction("Index");
        }

        public ActionResult UpdateBook(int id)
        {
            var updated = bookRepository.GetById(id);
            return View(updated);
        }

        [HttpPost]
        public ActionResult UpdateBook(Book book)
        {
            bookRepository.Update(book);

            return RedirectToAction("Index");
        }

        public ActionResult DeleteBook(int id)
        {
            var deleted = bookRepository.GetById(id);
            bookRepository.Delete(deleted);

            return RedirectToAction("Index");
        }
    }
}

LibraryProject.MvcWebUI/Controllers/CategoryController.cs
using LibraryProject.MvcWebUI.Models.Entity;
using LibraryProject.MvcWebUI.Models.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LibraryProject.MvcWebUI.Controllers
{
    public class CategoryController : Controller
    {
        BaseRepository<Category> categoryRepository = new BaseRepository<Category>();
        public ActionResult Index()
        {
            var categories = categoryRepository.GetList();
            return View(categories);
        }

        public ActionResult AddCategory()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddCategory(Category category)
        {
            categoryRepository.Add(category);
            return RedirectToAction("Index");
        }

        public ActionResult UpdateCategory(int id)
        {
            var updated = categoryRepository.GetById(id);
            return View(updated);
        }
        [HttpPost]
        public ActionResult UpdateCategory(Category category)
        {
            categoryRepository.Update(category);
            return RedirectToAction("Index");
        }
        public ActionResult DeleteCategory(int id)
        {
            var deleted = categoryRepository.GetById(id);
            categoryRepository.Delete(deleted);

            return RedirectToAction("Index");
        }
    }
}

LibraryProject.MvcWebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("Library", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Categories", "Index", "Category")</li>
                    <li>@Html.ActionLink("Books", "Index", "Book")</li>
                    <li></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    <footer class="text-center">
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>